// <auto-generated />
using Joel_Hilton_Film_Collection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Joel_Hilton_Film_Collection.Migrations
{
    [DbContext(typeof(EnterMoviesContext))]
    [Migration("20220203041248_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Joel_Hilton_Film_Collection.Models.Categories", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Category = "Action/Adventure"
                        },
                        new
                        {
                            CategoryID = 2,
                            Category = "Comedy"
                        },
                        new
                        {
                            CategoryID = 3,
                            Category = "Drama"
                        },
                        new
                        {
                            CategoryID = 4,
                            Category = "Family"
                        },
                        new
                        {
                            CategoryID = 5,
                            Category = "Miscellaneous"
                        },
                        new
                        {
                            CategoryID = 6,
                            Category = "Television"
                        },
                        new
                        {
                            CategoryID = 7,
                            Category = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryID = 8,
                            Category = "VHS"
                        });
                });

            modelBuilder.Entity("Joel_Hilton_Film_Collection.Models.EnterMovies", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LentTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Director = "Joss Whedon",
                            Edited = false,
                            LentTo = false,
                            Rating = "PG-13",
                            Title = "Avengers, The",
                            Year = 2012
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 1,
                            Director = "Tim Burton",
                            Edited = false,
                            LentTo = false,
                            Rating = "PG-13",
                            Title = "Batman",
                            Year = 1989
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 1,
                            Director = "Joel Schumacher",
                            Edited = false,
                            LentTo = false,
                            Rating = "PG-13",
                            Title = "Batman & Robin",
                            Year = 1997
                        });
                });

            modelBuilder.Entity("Joel_Hilton_Film_Collection.Models.EnterMovies", b =>
                {
                    b.HasOne("Joel_Hilton_Film_Collection.Models.Categories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
